name: cabdriver
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^1.0.7
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_messaging: ^13.0.3
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  geocoder2: ^1.4.0
  geocoding: ^3.0.0
  geoflutterfire: ^3.0.0-nullsafety.2
  geolocator: ^12.0.0
  get_it: ^7.7.0
  google_maps_flutter: ^2.6.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.6
  location: ^6.0.2
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
